### ISSUE TITLE
Photos

### ISSUE THREAD

**Issue by thecodeduchess** [GitJumped/prj-rev-bwfs-dasmoto#3]
https://github.com/GitJumped/prj-rev-bwfs-dasmoto/blob/68ea7a4660da24f60bf78f13174faefd79068759/Dasmotos/index.html#L12

Proper linking to photos. In the future, you will learn to how host these picture files and resources locally within your project.

The benefit of that is, your project will always be online if the site hosting your images is down.

**Comment by GitJumped** [comment]
Makes perfect sense, I was actually wondering about whether I should DL the images and include them in the resources folder, or utilize URLs.  Since the lessons thus far have used URLs, I stuck with that.  Thank you, I appreciate the feedback!
